version: '2'

services:
  bitbucket:
    image: asos/bitbucket
    hostname: bitbucket
    volumes:
      - /data/atlassian/bitbucket:/var/atlassian/bitbucket
    ports:
      - '7990:7990'
      - '7999:7999'
    environment:
      - 'BITBUCKET_PROXY_NAME='
      - 'BITBUCKET_PROXY_PORT='
      - 'BITBUCKET_PROXY_SCHEME='
      - 'BITBUCKET_DELAYED_START='
    labels:
      com.asos.description: "Atlassian Bitbucket"
      com.asos.service: "bitbucket"
      io.rancher.scheduler.affinity:host_label: host=atlassian
      io.rancher.container.pull_image: always
